name: 버그 발견
description: 버그를 발견했을 때 사용하는 이슈 템플릿입니다.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: content
    attributes:
      label: 내용
      description: 재현 방법, 기대 결과, 실제 결과, 첨부 자료 등을 자유롭게 작성해주세요.
      value: |
        ### 재현 단계
        1.
        2.
        3.
        (예: 보관소 관리자로 로그인 → 확인요청 승인버튼 클릭 → 우상단에 오류 발생)

        ### 원래 결과
        (예: 승인 버튼 클릭 시 분실물의 상태가 매칭완료로 바뀌어야 함)

        ### 실제 결과
        (예: 승인 버튼 클릭 시 분실물 상태가 변경되지 않고 우측 상단에 오류가 뜸)

        ### 첨부 사진
        (예: png, jpg, jpeg 등을 첨부해주세요.)
    validations:
      required: true
